# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- production

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        containerRegistry: 'DockerHub'
        repository: 'emmanuelpereira/ademir-bot'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
          $(tag)
    
    - task: SSH@0
      displayName: Update Docker Digital Ocean
      inputs:
        sshEndpoint: 'SSH VPS'
        runOptions: 'commands'
        commands: |
          docker pull emmanuelpereira/ademir-bot:$(tag)
          docker stop ademir
          docker system prune --force
          docker rm -f ademir
          docker run --name=ademir --restart=always -v /var/ademir/.env:/App/.env -d emmanuelpereira/ademir-bot:$(tag)
        readyTimeout: '20000'
